### ISSUE TITLE
Issue while trying to reach a goal state where one block is left on the table, with no block over it

### ISSUE THREAD

**Issue by LightningNemesis** [Leajian/blocks-world#1]
![blocksworld](https://user-images.githubusercontent.com/41684878/115600129-f4a5e000-a2f9-11eb-8f49-37bcc92ebb61.png)

I was trying to solve this problem using the code that you have provided (which is awesome btw), but I was unable to create a Goal State like the one in the image. 
Specifically, how do we address cases where the block is just on the table with nothing over it. For more clarity, I wanted to try a goal state like this: 

goalTemp = [('E', 'A'), ('B', ' '), ('C', 'D')] 
#### Here the tuple with 'B' has been kept as ' ' (empty space) denoting table, but I am getting a key error.

Any help would be hugely appreciated :)

**Comment by fregkos** [comment]
I know I've documented this in Greek, but you ~~should~~ can always check the comments for further explanation. I tried being super analytical, that's why I'll recommend you try to understand how I've implemented the [bwStateObject](https://github.com/Leajian/blocks-world/blob/63c1a6126b36b159e72684bb10fcc5c59861fd3c/bwStateObject.py) first.

Let's see part of the comments for the description of the state class:

> A state's description dictionary looks like this...
> {'A': ['B', True], 'C': ['table', True], 'B': ['table', False]}
> And represents...
> 'That cube': ['is on top of that', is it clear on top?]

First of all, states' descriptions (meaning how they are placed) are represented with dictionaries, not lists with tuples. I understand why you'd like to use an immutable type for something that won't change, such as a goal state. However, I tried being consistent, thus I used mutable type data (list in a dictionary) for the description of state objects, simply because I am "moving the blocks".
So, your goal state's description could be represented like this:

```
goalDesc = {'A': ['table', False], 'E': ['A', True], 'B': ['table', True], 'D': ['table', False], 'D': ['C', True]}
goalState = State(goalDesc)
```

If you wonder why I keep if a block is clear above, I need that to calculate children states. To move a block onto somewhere, it needs to be clear. I can't squeeze it between others. If there was another way to deduce if a block was clear above, it'll probably add more complexity, whereas I just use some more ram.

I'll recommend you check out 2 other solutions of some friends. If I remember correctly, the first is similar to mine, but I think we implemented the hashing method differently and the other performs faster for A*.
https://github.com/kouzapo/blocks-world
https://github.com/apostolistselios/blocks-world-ai

I'm closing this as it is not an issue with the code. You can continue with the conversation.
